package com.nocobase.ddl;

import com.nocobase.field.FieldOptions;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Database dialect adapter for generating DDL statements.
 * Hides dialect-specific SQL differences behind a common interface.
 */
public interface DialectAdapter {

    /**
     * Quote an identifier (table name, column name, etc.) for safe SQL usage.
     */
    String quoteIdentifier(String identifier);

    /**
     * Return the AUTO_INCREMENT / GENERATED BY DEFAULT AS IDENTITY clause.
     */
    String autoIncrementClause();

    /**
     * Map a field type to the database column type.
     */
    String mapFieldType(String fieldType, Integer length, Integer precision, Integer scale);

    /**
     * Generate the SQL for creating a table.
     */
    String buildCreateTable(String tableName, java.util.List<DdlPlan.ColumnDef> columns);

    /**
     * Generate the SQL for adding a column to a table.
     */
    String buildAddColumn(String tableName, DdlPlan.ColumnDef column);

    /**
     * Generate the SQL for dropping a column.
     */
    String buildDropColumn(String tableName, String columnName);

    /**
     * Generate the SQL for creating an index (supports multi-column indexes).
     */
    String buildCreateIndex(String tableName, String indexName, java.util.List<String> columnNames, boolean unique);

    /**
     * Generate the SQL for dropping an index.
     */
    String buildDropIndex(String indexName);

    /**
     * Check whether an index exists on the given table.
     * H2: queries INFORMATION_SCHEMA.INDEXES.
     * PostgreSQL: queries pg_indexes.
     *
     * @param jdbcTemplate the JdbcTemplate for the current datasource
     * @param tableName    the physical table name
     * @param indexName    the index name to check
     * @return true if the index exists
     */
    boolean indexExists(JdbcTemplate jdbcTemplate, String tableName, String indexName);

    /**
     * Check whether a table exists in the current database.
     * H2: queries INFORMATION_SCHEMA.TABLES.
     * PostgreSQL: queries pg_catalog.pg_tables.
     *
     * @param jdbcTemplate the JdbcTemplate for the current datasource
     * @param tableName    the physical table name
     * @return true if the table exists
     */
    boolean tableExists(JdbcTemplate jdbcTemplate, String tableName);

    /**
     * Check whether a column exists in a table.
     * H2: queries INFORMATION_SCHEMA.COLUMNS.
     * PostgreSQL: queries pg_catalog.pg_attribute / information_schema.columns.
     *
     * @param jdbcTemplate the JdbcTemplate for the current datasource
     * @param tableName    the physical table name
     * @param columnName   the column name to check
     * @return true if the column exists
     */
    boolean columnExists(JdbcTemplate jdbcTemplate, String tableName, String columnName);

    /**
     * Format a default value into a SQL-safe DEFAULT clause fragment.
     * <ul>
     *   <li>LITERAL strings: {@code 'escaped value'} with single-quote escaping</li>
     *   <li>LITERAL numbers: raw value (e.g. {@code 42}, {@code 3.14})</li>
     *   <li>LITERAL booleans: {@code TRUE} or {@code FALSE}</li>
     *   <li>EXPRESSION: passed through as-is (pre-validated allowlist)</li>
     * </ul>
     *
     * @param defaultValue the default value descriptor
     * @return the SQL fragment for the DEFAULT clause (never null)
     */
    default String formatDefaultValue(FieldOptions.DefaultValue defaultValue) {
        if (defaultValue == null) return null;
        if (defaultValue.isExpression()) {
            return defaultValue.getValue();
        }
        String val = defaultValue.getValue();
        // Try to parse as integer
        try {
            Long.parseLong(val);
            return val;
        } catch (NumberFormatException ignored) {
            // not an integer
        }
        // Try to parse as double
        try {
            Double.parseDouble(val);
            return val;
        } catch (NumberFormatException ignored) {
            // not a double
        }
        // Check for boolean
        if ("true".equalsIgnoreCase(val)) return "TRUE";
        if ("false".equalsIgnoreCase(val)) return "FALSE";
        // String literal — escape single quotes and wrap
        return "'" + val.replace("'", "''") + "'";
    }
}