package com.nocobase.ddl;

import com.nocobase.sql.SqlIdentifier;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * PostgreSQL dialect adapter.
 */
public class PostgresDialectAdapter implements DialectAdapter {

    private static final Map<String, String> TYPE_MAP = Map.ofEntries(
            Map.entry("string", "VARCHAR(255)"),
            Map.entry("text", "TEXT"),
            Map.entry("integer", "INTEGER"),
            Map.entry("bigint", "BIGINT"),
            Map.entry("float", "REAL"),
            Map.entry("double", "DOUBLE PRECISION"),
            Map.entry("boolean", "BOOLEAN"),
            Map.entry("date", "DATE"),
            Map.entry("datetime", "TIMESTAMP"),
            Map.entry("json", "JSONB"),
            Map.entry("uuid", "UUID"),
            Map.entry("password", "VARCHAR(255)"),
            Map.entry("decimal", "DECIMAL"),
            Map.entry("numeric", "NUMERIC")
    );

    @Override
    public String quoteIdentifier(String identifier) {
        return SqlIdentifier.quote(identifier);
    }

    @Override
    public String autoIncrementClause() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String mapFieldType(String fieldType, Integer length, Integer precision, Integer scale) {
        if (fieldType == null) return "VARCHAR(255)";
        String lower = fieldType.toLowerCase();
        String base = TYPE_MAP.getOrDefault(lower, "VARCHAR(255)");

        // Handle VARCHAR types with length
        if (length != null && base.contains("VARCHAR")) {
            base = "VARCHAR(" + length + ")";
        }

        // Handle decimal/numeric types with precision and scale
        if ((precision != null || scale != null) && (lower.equals("decimal") || lower.equals("numeric"))) {
            int p = precision != null ? precision : 10;
            if (scale != null) {
                base = base + "(" + p + ", " + scale + ")";
            } else {
                base = base + "(" + p + ")";
            }
        }

        return base;
    }

    @Override
    public String buildCreateTable(String tableName, List<DdlPlan.ColumnDef> columns) {
        StringBuilder sb = new StringBuilder("CREATE TABLE ");
        sb.append(quoteIdentifier(tableName)).append(" (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(columns.get(i).toSql(this));
        }
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String buildAddColumn(String tableName, DdlPlan.ColumnDef column) {
        return "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + column.toSql(this);
    }

    @Override
    public String buildDropColumn(String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(tableName) + " DROP COLUMN " + quoteIdentifier(columnName);
    }

    @Override
    public String buildCreateIndex(String tableName, String indexName, List<String> columnNames, boolean unique) {
        String type = unique ? "CREATE UNIQUE INDEX " : "CREATE INDEX ";
        String columns = columnNames.stream()
                .map(this::quoteIdentifier)
                .collect(Collectors.joining(", "));
        return type + quoteIdentifier(indexName) + " ON " + quoteIdentifier(tableName)
                + " (" + columns + ")";
    }

    @Override
    public String buildDropIndex(String indexName) {
        return "DROP INDEX IF EXISTS " + quoteIdentifier(indexName);
    }

    @Override
    public boolean indexExists(JdbcTemplate jdbcTemplate, String tableName, String indexName) {
        Long count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM pg_indexes WHERE tablename = ? AND indexname = ?",
                Long.class, tableName.toLowerCase(), indexName.toLowerCase());
        return count != null && count > 0;
    }

    @Override
    public boolean tableExists(JdbcTemplate jdbcTemplate, String tableName) {
        try {
            Long count = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM pg_catalog.pg_tables WHERE tablename = ?",
                    Long.class, tableName.toLowerCase());
            return count != null && count > 0;
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public boolean columnExists(JdbcTemplate jdbcTemplate, String tableName, String columnName) {
        try {
            Long count = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = ? AND column_name = ?",
                    Long.class, tableName.toLowerCase(), columnName.toLowerCase());
            return count != null && count > 0;
        } catch (Exception e) {
            return false;
        }
    }
}