package com.nocobase.sql;

import com.nocobase.config.NocobaseDataSourceProperties;
import com.nocobase.data.DynamicRepository;
import com.nocobase.ddl.DdlSynchronizer;
import com.nocobase.entity.*;
import com.nocobase.repository.*;
import com.nocobase.runtime.CollectionRuntimeService;
import com.nocobase.web.ForbiddenException;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link SqlDataSourceResolver} with a second H2 datasource.
 *
 * <p>Configures an "analytics" H2 in-memory database as an external data source,
 * creates a SQL collection that reads from it, and verifies:
 * <ul>
 *   <li>LIST returns data from the analytics DB</li>
 *   <li>ACL scope still applies on the SQL collection</li>
 *   <li>Main DB metadata is unaffected</li>
 *   <li>Caching works (same JdbcTemplate returned for repeated calls)</li>
 *   <li>External datasource is configured read-only</li>
 *   <li>Error messages are sanitized</li>
 * </ul>
 */
@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "nocobase.data-sources.analytics.url=jdbc:h2:mem:analytics;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "nocobase.data-sources.analytics.driver-class-name=org.h2.Driver",
        "nocobase.data-sources.analytics.username=sa",
        "nocobase.data-sources.analytics.password=",
        "nocobase.data-sources.analytics.enabled=true",
        "nocobase.data-sources.analytics.read-only=true",
        "nocobase.data-sources.reporting.url=jdbc:h2:mem:reporting;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "nocobase.data-sources.reporting.driver-class-name=org.h2.Driver",
        "nocobase.data-sources.reporting.username=sa",
        "nocobase.data-sources.reporting.password=",
        "nocobase.data-sources.reporting.enabled=true",
        "nocobase.data-sources.reporting.read-only=true"
})
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SqlDataSourceResolverIntegrationTest {

    @Autowired private SqlDataSourceResolver resolver;
    @Autowired private CollectionRuntimeService runtimeService;
    @Autowired private DdlSynchronizer ddlSynchronizer;
    @Autowired private DynamicRepository dynamicRepository;
    @Autowired private JdbcTemplate jdbcTemplate;
    @Autowired private NocobaseDataSourceProperties dataSourceProperties;
    @Autowired private CollectionRepository collectionRepository;
    @Autowired private FieldRepository fieldRepository;
    @Autowired private UserRepository userRepository;
    @Autowired private RoleRepository roleRepository;
    @Autowired private RoleResourceRepository roleResourceRepository;
    @Autowired private RoleResourceActionRepository roleResourceActionRepository;
    @Autowired private RoleResourceScopeRepository roleResourceScopeRepository;
    @Autowired private UserRoleRepository userRoleRepository;

    private static final String ANALYTICS_TABLE = "analytics_metrics";
    private static final String SQL_COLL = "analytics_dashboard";
    private static final String SQL_COLL_PK = "analytics_dashboard_pk";
    private static final String ANALYTICS_URL = "jdbc:h2:mem:analytics;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

    private Long memberUserId;
    private Long metricIdA, metricIdB, metricIdC;

    @BeforeAll
    void setUp() throws Exception {
        authAsAdmin();

        // ── Set up the analytics table using a direct JDBC connection ──
        // We use a direct connection (not the resolver) because the resolver
        // creates read-only datasources, and we need to CREATE TABLE / INSERT.
        try (Connection conn = DriverManager.getConnection(ANALYTICS_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute(
                    "CREATE TABLE IF NOT EXISTS \"" + ANALYTICS_TABLE + "\" (" +
                    "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "\"metric_name\" VARCHAR(255) NOT NULL, " +
                    "\"metric_value\" DOUBLE NOT NULL, " +
                    "\"category\" VARCHAR(100), " +
                    "\"owner_id\" BIGINT" +
                    ")");
            stmt.execute("DELETE FROM \"" + ANALYTICS_TABLE + "\"");
            stmt.execute("INSERT INTO \"" + ANALYTICS_TABLE + "\" (\"metric_name\", \"metric_value\", \"category\", \"owner_id\") VALUES ('Page Views', 1500.0, 'traffic', 1)");
            stmt.execute("INSERT INTO \"" + ANALYTICS_TABLE + "\" (\"metric_name\", \"metric_value\", \"category\", \"owner_id\") VALUES ('Sessions', 320.0, 'traffic', 1)");
            stmt.execute("INSERT INTO \"" + ANALYTICS_TABLE + "\" (\"metric_name\", \"metric_value\", \"category\", \"owner_id\") VALUES ('Bounce Rate', 42.5, 'engagement', 2)");
        }

        // Capture generated IDs via the resolver (SELECT is allowed on read-only)
        JdbcTemplate analyticsJdbc = resolver.resolve("analytics");
        metricIdA = analyticsJdbc.queryForObject(
                "SELECT \"id\" FROM \"" + ANALYTICS_TABLE + "\" WHERE \"metric_name\" = ?", Long.class, "Page Views");
        metricIdB = analyticsJdbc.queryForObject(
                "SELECT \"id\" FROM \"" + ANALYTICS_TABLE + "\" WHERE \"metric_name\" = ?", Long.class, "Sessions");
        metricIdC = analyticsJdbc.queryForObject(
                "SELECT \"id\" FROM \"" + ANALYTICS_TABLE + "\" WHERE \"metric_name\" = ?", Long.class, "Bounce Rate");

        // ── Create SQL collection (no primary key) ──
        if (!runtimeService.exists(SQL_COLL)) {
            CollectionEntity sqlColl = new CollectionEntity(SQL_COLL, "Analytics Dashboard", "sql");
            sqlColl.setSql("SELECT \"id\", \"metric_name\", \"metric_value\", \"category\", \"owner_id\" FROM \"" + ANALYTICS_TABLE + "\"");
            sqlColl.setOptions("{\"dataSourceKey\": \"analytics\"}");
            ddlSynchronizer.createCollection(sqlColl, List.of(
                    new FieldEntity(SQL_COLL, "id", "bigInt"),
                    new FieldEntity(SQL_COLL, "metric_name", "string"),
                    new FieldEntity(SQL_COLL, "metric_value", "float"),
                    new FieldEntity(SQL_COLL, "category", "string"),
                    new FieldEntity(SQL_COLL, "owner_id", "bigInt")));
            runtimeService.reload(SQL_COLL);
        }

        // ── Create SQL collection with primary key ──
        if (!runtimeService.exists(SQL_COLL_PK)) {
            CollectionEntity sqlCollPk = new CollectionEntity(SQL_COLL_PK, "Analytics Dashboard PK", "sql");
            sqlCollPk.setSql("SELECT \"id\", \"metric_name\", \"metric_value\", \"category\", \"owner_id\" FROM \"" + ANALYTICS_TABLE + "\"");
            sqlCollPk.setOptions("{\"primaryKey\": \"id\", \"dataSourceKey\": \"analytics\"}");
            ddlSynchronizer.createCollection(sqlCollPk, List.of(
                    new FieldEntity(SQL_COLL_PK, "id", "bigInt"),
                    new FieldEntity(SQL_COLL_PK, "metric_name", "string"),
                    new FieldEntity(SQL_COLL_PK, "metric_value", "float"),
                    new FieldEntity(SQL_COLL_PK, "category", "string"),
                    new FieldEntity(SQL_COLL_PK, "owner_id", "bigInt")));
            runtimeService.reload(SQL_COLL_PK);
        }

        // ── Create member user for ACL tests ──
        String memberEmail = "ds_resolver_member@test.com";
        User member = userRepository.findByEmail(memberEmail).orElse(null);
        if (member != null) {
            memberUserId = member.getId();
        } else {
            member = new User();
            member.setEmail(memberEmail);
            member.setNickname("DS Resolver Member");
            member.setPassword("encoded");
            member = userRepository.save(member);
            memberUserId = member.getId();
        }

        // ── Ensure admin user exists for main DB tests ──
        // Tests like mainDbMetadataUnaffected and badJdbcUrl_sqlCollectionInvalid_mainSystemUnaffected
        // query the users table. The admin user should exist (created by TestDataInitializer),
        // but if the context is reused or tables are recreated, create it explicitly.
        // Use JdbcTemplate for direct insertion to ensure the row is visible to
        // DynamicRepository queries which use the same JdbcTemplate.
        userRepository.findByEmail("admin@nocobase.com").orElseGet(() -> {
            User admin = new User();
            admin.setEmail("admin@nocobase.com");
            admin.setNickname("Admin");
            admin.setPassword("encoded");
            return userRepository.save(admin);
        });
        // Also ensure at least one user row exists directly via JdbcTemplate
        // in case the JPA save is not yet visible to DynamicRepository's JdbcTemplate.
        Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM \"users\"", Integer.class);
        if (userCount != null && userCount == 0) {
            jdbcTemplate.update("INSERT INTO \"users\" (\"email\", \"nickname\", \"password\") VALUES (?, ?, ?)",
                    "admin@nocobase.com", "Admin", "encoded");
        }

        Role memberRole = roleRepository.findByName("member").orElse(null);
        if (memberRole == null) fail("member role not found");
        boolean alreadyBound = userRoleRepository.findByUserId(memberUserId).stream()
                .anyMatch(ur -> ur.getRoleId().equals(memberRole.getId()));
        if (!alreadyBound) {
            UserRole ur = new UserRole();
            ur.setUserId(memberUserId);
            ur.setRoleId(memberRole.getId());
            userRoleRepository.save(ur);
        }
    }

    @AfterAll
    void tearDown() throws Exception {
        authAsAdmin();

        // Drop the analytics table using a direct connection
        try (Connection conn = DriverManager.getConnection(ANALYTICS_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS \"" + ANALYTICS_TABLE + "\"");
        } catch (Exception e) {
            // ignore cleanup errors
        }

        // Clean up ACL permissions
        cleanupMemberPermissions(SQL_COLL);
        cleanupMemberPermissions(SQL_COLL_PK);

        // Delete SQL collection metadata from the database
        // so that the next test run doesn't try to load stale SQL collections
        try {
            collectionRepository.findByName(SQL_COLL).ifPresent(coll -> {
                fieldRepository.findByCollectionName(SQL_COLL).forEach(fieldRepository::delete);
                collectionRepository.delete(coll);
            });
            collectionRepository.findByName(SQL_COLL_PK).ifPresent(coll -> {
                fieldRepository.findByCollectionName(SQL_COLL_PK).forEach(fieldRepository::delete);
                collectionRepository.delete(coll);
            });
            // Also clean up the member user
            if (memberUserId != null) {
                userRoleRepository.findByUserId(memberUserId).forEach(userRoleRepository::delete);
                userRepository.deleteById(memberUserId);
            }
        } catch (Exception e) {
            // ignore cleanup errors
        }

        // Reload runtime to remove SQL collections
        runtimeService.reloadAll();
    }

    @BeforeEach
    void resetAuth() {
        authAsAdmin();
    }

    // ═══════════════════════════════════════════════════════════════════
    // Resolver registry tests
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("resolve 'analytics' returns non-null JdbcTemplate")
    void resolveAnalyticsReturnsJdbcTemplate() {
        JdbcTemplate jdbc = resolver.resolve("analytics");
        assertNotNull(jdbc, "analytics JdbcTemplate should not be null");
    }

    @Test
    @DisplayName("resolve 'analytics' returns same instance on repeated calls (caching)")
    void resolveAnalyticsCachesInstance() {
        JdbcTemplate first = resolver.resolve("analytics");
        JdbcTemplate second = resolver.resolve("analytics");
        assertSame(first, second, "Same JdbcTemplate instance should be returned on repeated calls");
    }

    @Test
    @DisplayName("resolve 'main' still returns the main JdbcTemplate")
    void resolveMainStillWorks() {
        JdbcTemplate main = resolver.resolve("main");
        assertNotNull(main, "main JdbcTemplate should not be null");
        // analytics should be a different instance
        JdbcTemplate analytics = resolver.resolve("analytics");
        assertNotSame(main, analytics, "main and analytics should be different JdbcTemplate instances");
    }

    @Test
    @DisplayName("resolve unconfigured key throws UnsupportedOperationException")
    void resolveUnconfiguredKeyThrows() {
        UnsupportedOperationException ex = assertThrows(
                UnsupportedOperationException.class,
                () -> resolver.resolve("nonexistent"),
                "Resolving unconfigured key should throw");
        assertTrue(ex.getMessage().contains("nonexistent"),
                "Error message should contain the key name");
    }

    // ═══════════════════════════════════════════════════════════════════
    // Data retrieval tests — verify data comes from analytics DB
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("LIST returns data from analytics database")
    void listReturnsDataFromAnalyticsDb() {
        var result = dynamicRepository.list(SQL_COLL, null, null, 1, 10, null);
        assertEquals(3, result.getCount(), "should see exactly 3 metrics from analytics DB");
        assertFalse(result.getData().isEmpty());

        // Verify data content matches what we inserted in analytics DB
        boolean hasPageViews = result.getData().stream()
                .anyMatch(r -> "Page Views".equals(r.get("metric_name")));
        boolean hasSessions = result.getData().stream()
                .anyMatch(r -> "Sessions".equals(r.get("metric_name")));
        boolean hasBounceRate = result.getData().stream()
                .anyMatch(r -> "Bounce Rate".equals(r.get("metric_name")));
        assertTrue(hasPageViews, "should contain Page Views metric");
        assertTrue(hasSessions, "should contain Sessions metric");
        assertTrue(hasBounceRate, "should contain Bounce Rate metric");
    }

    @Test
    @DisplayName("LIST with filter works on analytics data")
    void listWithFilterOnAnalyticsData() {
        var result = dynamicRepository.list(SQL_COLL,
                Map.of("category", "traffic"), null, 1, 10, null);
        assertEquals(2, result.getCount(), "should see exactly 2 traffic metrics");
        for (var row : result.getData()) {
            assertEquals("traffic", row.get("category"));
        }
    }

    @Test
    @DisplayName("LIST with sort works on analytics data")
    void listWithSortOnAnalyticsData() {
        var result = dynamicRepository.list(SQL_COLL, null, "-metric_value", 1, 10, null);
        assertEquals(3, result.getCount());
        if (result.getData().size() >= 2) {
            double first = ((Number) result.getData().get(0).get("metric_value")).doubleValue();
            double second = ((Number) result.getData().get(1).get("metric_value")).doubleValue();
            assertTrue(first >= second, "DESC sort should put higher metric_value first");
        }
    }

    @Test
    @DisplayName("LIST with pagination works on analytics data")
    void listWithPaginationOnAnalyticsData() {
        var page1 = dynamicRepository.list(SQL_COLL, null, "id", 1, 2, null);
        assertEquals(2, page1.getData().size(), "page 1 should have exactly 2 records");
        var page2 = dynamicRepository.list(SQL_COLL, null, "id", 2, 2, null);
        assertEquals(1, page2.getData().size(), "page 2 should have exactly 1 record");
    }

    @Test
    @DisplayName("GET with primary key returns correct analytics record")
    void getWithPrimaryKeyReturnsCorrectRecord() {
        var result = dynamicRepository.get(SQL_COLL_PK, metricIdA);
        assertNotNull(result, "get() should return the Page Views metric");
        assertEquals(metricIdA, result.get("id"));
        assertEquals("Page Views", result.get("metric_name"));
        assertEquals(1500.0, ((Number) result.get("metric_value")).doubleValue(), 0.001);
    }

    @Test
    @DisplayName("GET without primary key collection is rejected")
    void getWithoutPrimaryKeyIsRejected() {
        // SQL_COLL has no primaryKey configured
        assertThrows(Exception.class, () ->
                dynamicRepository.get(SQL_COLL, metricIdA));
    }

    // ═══════════════════════════════════════════════════════════════════
    // ACL scope tests — verify ACL still applies on external data
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("ACL scope applies on analytics SQL collection")
    void aclScopeAppliesOnAnalyticsCollection() {
        cleanupMemberPermissions(SQL_COLL);

        // Grant member list permission with scope: owner_id=1
        grantMemberPermissionWithScope(SQL_COLL, "list", "metric_name,category,metric_value,owner_id",
                "{\"owner_id\": {\"$eq\": 1}}");

        authAsMember();
        var result = dynamicRepository.list(SQL_COLL, null, null, 1, 100, null);
        assertEquals(2, result.getCount(), "member should only see 2 metrics with owner_id=1");
        for (var row : result.getData()) {
            assertEquals(1L, ((Number) row.get("owner_id")).longValue(),
                    "all records should have owner_id=1");
        }
    }

    @Test
    @DisplayName("ACL readable fields applies on analytics SQL collection")
    void aclReadableFieldsAppliesOnAnalyticsCollection() {
        cleanupMemberPermissions(SQL_COLL);

        // Grant member list permission with only metric_name and category readable
        grantMemberPermission(SQL_COLL, "list", "metric_name,category");

        authAsMember();
        var result = dynamicRepository.list(SQL_COLL, null, null, 1, 10, null);
        assertFalse(result.getData().isEmpty());
        Map<String, Object> first = result.getData().get(0);
        assertTrue(first.containsKey("metric_name"), "metric_name should be present");
        assertTrue(first.containsKey("category"), "category should be present");
        assertFalse(first.containsKey("metric_value"), "metric_value should NOT be present");
        assertFalse(first.containsKey("owner_id"), "owner_id should NOT be present");
    }

    @Test
    @DisplayName("Member without list permission gets ForbiddenException on analytics collection")
    void memberWithoutPermissionGetsForbidden() {
        cleanupMemberPermissions(SQL_COLL);

        authAsMember();
        assertThrows(ForbiddenException.class, () ->
                dynamicRepository.list(SQL_COLL, null, null, 1, 10, null));
    }

    @Test
    @DisplayName("ACL scope on get() applies on analytics collection with PK")
    void aclScopeOnGetAppliesOnAnalyticsCollection() {
        cleanupMemberPermissions(SQL_COLL_PK);

        // Grant member get permission with scope: owner_id=1
        // metricIdA and metricIdB have owner_id=1, metricIdC has owner_id=2
        grantMemberPermissionWithScope(SQL_COLL_PK, "get", "metric_name,category,metric_value,owner_id,id",
                "{\"owner_id\": {\"$eq\": 1}}");

        authAsMember();

        // get(metricIdA) should return the record (owner_id=1)
        Map<String, Object> resultA = dynamicRepository.get(SQL_COLL_PK, metricIdA);
        assertNotNull(resultA, "record with owner_id=1 should be returned");
        assertEquals("Page Views", resultA.get("metric_name"));

        // get(metricIdC) should return null (owner_id=2, not in scope)
        Map<String, Object> resultC = dynamicRepository.get(SQL_COLL_PK, metricIdC);
        assertNull(resultC, "record with owner_id=2 should not be returned (scope)");
    }

    // ═══════════════════════════════════════════════════════════════════
    // Main DB unaffected tests
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("Main DB metadata is unaffected by analytics datasource")
    void mainDbMetadataUnaffected() {
        // Verify main DB collections are still accessible
        assertTrue(runtimeService.exists("users"),
                "users collection should still exist in main DB");
        assertTrue(runtimeService.exists("roles"),
                "roles collection should still exist in main DB");

        // Verify the analytics SQL collection exists but is not a physical table in main DB
        assertTrue(runtimeService.exists(SQL_COLL),
                "analytics SQL collection should exist in runtime");

        // Verify main DB can still list users
        var result = dynamicRepository.list("users", null, null, 1, 10, null);
        assertNotNull(result.getData(), "main DB users list should still work");
        assertTrue(result.getCount() >= 1, "main DB should have at least 1 user");
    }

    @Test
    @DisplayName("Data from analytics DB does not appear in main DB")
    void analyticsDataDoesNotAppearInMainDb() {
        // The analytics_metrics table should NOT exist in the main DB
        // If we try to query it via the main JdbcTemplate, it should fail
        assertThrows(Exception.class, () ->
                jdbcTemplate.queryForList("SELECT * FROM \"" + ANALYTICS_TABLE + "\""));
    }

    // ═══════════════════════════════════════════════════════════════════
    // Read-only enforcement tests
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("External analytics datasource DataSource is configured as read-only")
    void externalDatasourceIsReadOnly() {
        JdbcTemplate analyticsJdbc = resolver.resolve("analytics");
        DataSource ds = analyticsJdbc.getDataSource();
        assertNotNull(ds, "DataSource should not be null");
        assertInstanceOf(HikariDataSource.class, ds,
                "external datasource should be backed by HikariDataSource");
        HikariDataSource hds = (HikariDataSource) ds;
        assertTrue(hds.isReadOnly(),
                "external datasource should be configured as read-only");
    }

    @Test
    @DisplayName("SQL collection create/update/destroy are rejected (read-only semantics)")
    void sqlCollectionWritesAreRejected() {
        // SQL collections are always read-only regardless of data source
        assertThrows(ForbiddenException.class, () ->
                dynamicRepository.create(SQL_COLL, Map.of("metric_name", "test")));
        assertThrows(ForbiddenException.class, () ->
                dynamicRepository.update(SQL_COLL, metricIdA, Map.of("metric_name", "test")));
        assertThrows(ForbiddenException.class, () ->
                dynamicRepository.destroy(SQL_COLL, metricIdA));
    }

    // ═══════════════════════════════════════════════════════════════════
    // Error sanitization tests
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("Connection error message is sanitized (no URL/password leakage)")
    void connectionErrorIsSanitized() {
        // The 'warehouse' datasource is not configured — verify error message
        // does not contain any SQL or connection details
        UnsupportedOperationException ex = assertThrows(
                UnsupportedOperationException.class,
                () -> resolver.resolve("warehouse"));
        String msg = ex.getMessage();
        assertFalse(msg.contains("jdbc:"), "error should not contain JDBC URL");
        assertFalse(msg.contains("password"), "error should not contain password");
        assertFalse(msg.contains("SELECT"), "error should not contain SQL");
    }

    // ═══════════════════════════════════════════════════════════════════
    // DataSource lifecycle tests
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("clearUnavailable closes external HikariDataSource")
    void clearUnavailableClosesExternalDataSource() {
        // Resolve creates the external datasource lazily
        JdbcTemplate analyticsJdbc = resolver.resolve("analytics");
        assertNotNull(analyticsJdbc);

        DataSource ds = analyticsJdbc.getDataSource();
        assertInstanceOf(HikariDataSource.class, ds);
        HikariDataSource hds = (HikariDataSource) ds;
        assertFalse(hds.isClosed(), "external datasource should be open before cleanup");

        // clearUnavailable() must close the connection pool
        resolver.clearUnavailable();

        assertTrue(hds.isClosed(), "external datasource should be closed after clearUnavailable");
    }

    @Test
    @DisplayName("clearUnavailable closes all external data sources")
    void clearUnavailableClosesAllExternalDataSources() {
        // Create both "analytics" and "reporting" external datasources
        JdbcTemplate analyticsJdbc = resolver.resolve("analytics");
        JdbcTemplate reportingJdbc = resolver.resolve("reporting");

        HikariDataSource analyticsHds = (HikariDataSource) analyticsJdbc.getDataSource();
        HikariDataSource reportingHds = (HikariDataSource) reportingJdbc.getDataSource();

        assertFalse(analyticsHds.isClosed(), "analytics should be open");
        assertFalse(reportingHds.isClosed(), "reporting should be open");

        resolver.clearUnavailable();

        assertTrue(analyticsHds.isClosed(), "analytics should be closed");
        assertTrue(reportingHds.isClosed(), "reporting should be closed");
    }

    @Test
    @DisplayName("main datasource is NOT closed by resolver cleanup")
    void mainDatasourceNotClosedByResolver() {
        // Resolve the main JdbcTemplate and get its underlying DataSource
        JdbcTemplate mainJdbc = resolver.resolve("main");
        DataSource mainDs = mainJdbc.getDataSource();
        assertNotNull(mainDs, "main DataSource should not be null");

        // Resolve an external datasource to populate the registry
        resolver.resolve("analytics");

        // Call cleanup — external datasources are closed, but main must NOT be
        resolver.clearUnavailable();

        // The main datasource is managed by Spring Boot; the resolver must
        // never close it. We verify it's still usable by getting a connection.
        assertDoesNotThrow(() -> {
            try (Connection conn = mainDs.getConnection()) {
                assertNotNull(conn);
                assertFalse(conn.isClosed(), "main datasource connection should be open");
            }
        }, "main datasource should remain open and usable after resolver cleanup");
    }

    @Test
    @DisplayName("destroy() closes all external data sources (simulates shutdown)")
    void destroyClosesAllExternalDataSources() {
        // Create both external datasources
        JdbcTemplate analyticsJdbc = resolver.resolve("analytics");
        JdbcTemplate reportingJdbc = resolver.resolve("reporting");

        HikariDataSource analyticsHds = (HikariDataSource) analyticsJdbc.getDataSource();
        HikariDataSource reportingHds = (HikariDataSource) reportingJdbc.getDataSource();

        assertFalse(analyticsHds.isClosed(), "analytics should be open before destroy");
        assertFalse(reportingHds.isClosed(), "reporting should be open before destroy");

        // Simulate Spring shutdown by calling destroy() directly
        resolver.destroy();

        assertTrue(analyticsHds.isClosed(), "analytics should be closed after destroy");
        assertTrue(reportingHds.isClosed(), "reporting should be closed after destroy");
    }

    @Test
    @DisplayName("main datasource is NOT closed by destroy()")
    void mainDatasourceNotClosedByDestroy() {
        JdbcTemplate mainJdbc = resolver.resolve("main");
        DataSource mainDs = mainJdbc.getDataSource();
        assertNotNull(mainDs);

        // Populate external datasources
        resolver.resolve("analytics");
        resolver.resolve("reporting");

        // Simulate shutdown
        resolver.destroy();

        // Main datasource must still be usable
        assertDoesNotThrow(() -> {
            try (Connection conn = mainDs.getConnection()) {
                assertNotNull(conn);
                assertFalse(conn.isClosed(), "main datasource connection should be open");
            }
        }, "main datasource should remain open and usable after destroy()");
    }

    // ═══════════════════════════════════════════════════════════════════
    // P0-D: Bad JDBC URL → invalid collection, main system unaffected
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("P0-D: Bad JDBC URL → resolve fails, datasource marked unavailable")
    void badJdbcUrl_resolveFails_markedUnavailable() {
        // Register a datasource with a bad URL at runtime
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0d-bad-ds", badConfig);

        // Resolve should fail — connection cannot be established
        assertThrows(DataSourceUnavailableException.class,
                () -> resolver.resolve("p0d-bad-ds"),
                "Resolving a datasource with a bad JDBC URL should throw");

        // Datasource should be marked as unavailable
        assertFalse(resolver.isAvailable("p0d-bad-ds"),
                "Datasource with bad URL should be marked unavailable");

        // Cleanup
        resolver.clearUnavailable();
        dataSourceProperties.getDataSources().remove("p0d-bad-ds");
    }

    @Test
    @DisplayName("P0-D: Bad JDBC URL → SQL collection invalid, main system unaffected")
    void badJdbcUrl_sqlCollectionInvalid_mainSystemUnaffected() {
        // Register a datasource with a bad URL
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0d-bad-ext", badConfig);

        // Create a SQL collection referencing the bad datasource
        String collName = "p0d_bad_ds_coll";
        try {
            CollectionEntity entity = new CollectionEntity(collName, "Bad DS Coll", "sql");
            entity.setSql("SELECT 1 AS \"id\", 'test' AS \"name\"");
            entity.setOptions("{\"dataSourceKey\": \"p0d-bad-ext\"}");
            ddlSynchronizer.createCollection(entity, List.of(
                    new FieldEntity(collName, "id", "bigInt"),
                    new FieldEntity(collName, "name", "string")));

            // reload() should throw — the datasource is unavailable
            assertThrows(RuntimeException.class,
                    () -> runtimeService.reload(collName),
                    "Reloading collection with bad datasource should throw");

            // Collection should be tracked as invalid
            assertTrue(runtimeService.getInvalidCollections().containsKey(collName),
                    "Collection should be in invalidCollections");

            // Main system should be unaffected — users collection still works
            assertTrue(runtimeService.exists("users"),
                    "Main system collections should still be available");
            var result = dynamicRepository.list("users", null, null, 1, 10, null);
            assertNotNull(result.getData(), "Main DB should still work");

            // Error message should NOT contain JDBC URL
            String errorMsg = runtimeService.getInvalidCollections().get(collName);
            assertNotNull(errorMsg);
            assertFalse(errorMsg.contains("jdbc:"),
                    "Error message should not contain JDBC URL");
            assertFalse(errorMsg.contains("tcp:"),
                    "Error message should not contain connection details");
            assertFalse(errorMsg.contains("19999"),
                    "Error message should not contain port number");
        } finally {
            // Cleanup
            try { runtimeService.reload(collName); } catch (Exception ignored) {}
            try {
                List<FieldEntity> fields = fieldRepository.findByCollectionName(collName);
                fieldRepository.deleteAll(fields);
                collectionRepository.findByName(collName).ifPresent(collectionRepository::delete);
            } catch (Exception ignored) {}
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0d-bad-ext");
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    // P0-E: Unavailable DataSource recovery strategy
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("P0-E: First connection fails → datasource unavailable, collection invalid")
    void firstConnectionFails_datasourceUnavailable() {
        // Register a datasource with a bad URL
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0e-recover-ds", badConfig);

        try {
            // First resolve attempt should fail
            assertThrows(DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0e-recover-ds"),
                    "First resolve with bad URL should fail");

            // Datasource should be unavailable
            assertFalse(resolver.isAvailable("p0e-recover-ds"),
                    "Datasource should be unavailable after failed connection");
        } finally {
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0e-recover-ds");
        }
    }

    @Test
    @DisplayName("P0-E: Fix datasource URL, call refreshDataSource → recovers successfully")
    void fixDatasourceUrl_refreshDataSource_recovers() {
        // Register a datasource with a bad URL
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0e-recover2-ds", badConfig);

        try {
            // First resolve should fail
            assertThrows(DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0e-recover2-ds"));
            assertFalse(resolver.isAvailable("p0e-recover2-ds"));

            // Fix the URL to a valid H2 in-memory database
            dataSourceProperties.getDataSources().get("p0e-recover2-ds")
                    .setUrl("jdbc:h2:mem:p0e_recovered;DB_CLOSE_DELAY=-1");

            // Call refreshDataSource — should succeed
            boolean recovered = resolver.refreshDataSource("p0e-recover2-ds");
            assertTrue(recovered, "refreshDataSource should return true after fixing URL");

            // Datasource should now be available
            assertTrue(resolver.isAvailable("p0e-recover2-ds"),
                    "Datasource should be available after recovery");

            // Should be able to resolve and use it
            JdbcTemplate jdbc = resolver.resolve("p0e-recover2-ds");
            assertNotNull(jdbc, "Should be able to resolve after recovery");
            // Execute a simple query to confirm it works
            Integer result = jdbc.queryForObject("SELECT 1", Integer.class);
            assertEquals(1, result, "Simple query should work on recovered datasource");

        } finally {
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0e-recover2-ds");
        }
    }

    @Test
    @DisplayName("P0-E: Fix datasource, call runtimeService.reload() → collection loads successfully")
    void fixDatasource_reloadCollection_succeeds() {
        String collName = "p0e_recover_coll";
        // Register a datasource with a bad URL
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0e-recover3-ds", badConfig);

        try {
            // Create a SQL collection referencing the bad datasource
            CollectionEntity entity = new CollectionEntity(collName, "Recover Coll", "sql");
            entity.setSql("SELECT 1 AS \"id\", 'test' AS \"name\"");
            entity.setOptions("{\"dataSourceKey\": \"p0e-recover3-ds\"}");
            ddlSynchronizer.createCollection(entity, List.of(
                    new FieldEntity(collName, "id", "bigInt"),
                    new FieldEntity(collName, "name", "string")));

            // First reload should fail
            assertThrows(RuntimeException.class,
                    () -> runtimeService.reload(collName));
            assertTrue(runtimeService.getInvalidCollections().containsKey(collName),
                    "Collection should be invalid initially");

            // Fix the datasource URL
            dataSourceProperties.getDataSources().get("p0e-recover3-ds")
                    .setUrl("jdbc:h2:mem:p0e_recovered3;DB_CLOSE_DELAY=-1");

            // Reload the collection — should succeed now
            assertDoesNotThrow(() -> runtimeService.reload(collName),
                    "Reload should succeed after fixing datasource URL");

            // Collection should be in the registry
            assertTrue(runtimeService.exists(collName),
                    "Collection should be in registry after successful reload");

            // Collection should NOT be in invalidCollections
            assertFalse(runtimeService.getInvalidCollections().containsKey(collName),
                    "Collection should not be in invalidCollections after recovery");

            // The datasource should be available
            assertTrue(resolver.isAvailable("p0e-recover3-ds"),
                    "Datasource should be available after recovery");

            // Verify the collection is usable
            var result = dynamicRepository.list(collName, null, null, 1, 10, null);
            assertNotNull(result);
            assertEquals(1, result.getCount(), "Should return the single test row");

        } finally {
            // Cleanup
            try { runtimeService.reload(collName); } catch (Exception ignored) {}
            try {
                List<FieldEntity> fields = fieldRepository.findByCollectionName(collName);
                fieldRepository.deleteAll(fields);
                collectionRepository.findByName(collName).ifPresent(collectionRepository::delete);
            } catch (Exception ignored) {}
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0e-recover3-ds");
        }
    }

    @Test
    @DisplayName("P0-E: After recovery, isAvailable() returns true")
    void afterRecovery_isAvailableReturnsTrue() {
        // Register a datasource with a bad URL
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0e-avail-ds", badConfig);

        try {
            // Before any resolve attempt, isAvailable should return false
            // (the datasource is in config but hasn't been proven)
            assertFalse(resolver.isAvailable("p0e-avail-ds"),
                    "isAvailable should be false before datasource is resolved");

            // Resolve fails → marked unavailable
            assertThrows(DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0e-avail-ds"));
            assertFalse(resolver.isAvailable("p0e-avail-ds"),
                    "isAvailable should be false after failed connection");

            // Fix the URL
            dataSourceProperties.getDataSources().get("p0e-avail-ds")
                    .setUrl("jdbc:h2:mem:p0e_avail;DB_CLOSE_DELAY=-1");

            // Recover
            boolean recovered = resolver.refreshDataSource("p0e-avail-ds");
            assertTrue(recovered, "refreshDataSource should succeed");

            // Now isAvailable should return true
            assertTrue(resolver.isAvailable("p0e-avail-ds"),
                    "isAvailable should return true after successful recovery");

        } finally {
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0e-avail-ds");
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    // P0-B: Resource leak on failure path — DataSource lifecycle safety
    // ═══════════════════════════════════════════════════════════════════

    @Test
    @DisplayName("P0-B: Creation failure → no HikariDataSource created (preflight blocks pool init)")
    void creationFailure_noHikariDataSourceCreated() {
        // Register a datasource with a bad URL that will fail on preflight connection test
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0b-leak-ds", badConfig);

        try {
            // Resolve should fail — preflight with DriverManager catches the error
            // BEFORE any HikariDataSource is created, so Hikari never logs
            // raw "Exception during pool initialization" stack traces.
            DataSourceUnavailableException ex = assertThrows(
                    DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0b-leak-ds"),
                    "Resolving a datasource with bad URL should throw");

            // Error message must NOT contain JDBC URL, host, port, or password
            String msg = ex.getSanitizedReason();
            assertNotNull(msg);
            assertFalse(msg.toLowerCase().contains("jdbc:"),
                    "Error should not contain JDBC URL");
            assertFalse(msg.toLowerCase().contains("tcp:"),
                    "Error should not contain connection details");
            assertFalse(msg.toLowerCase().contains("19999"),
                    "Error should not contain port number");
            assertFalse(msg.toLowerCase().contains("password"),
                    "Error should not contain password");

            // Datasource should be marked unavailable
            assertFalse(resolver.isAvailable("p0b-leak-ds"),
                    "Datasource should be unavailable after failed preflight");

            // No HikariDataSource was ever created — no resource leak possible
        } finally {
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0b-leak-ds");
        }
    }

    @Test
    @DisplayName("P0-B: Preflight connection failure → no HikariDataSource created, no resource leak")
    void preflightConnectionFailure_noHikariDataSourceCreated() {
        // Register a datasource with a bad URL — preflight with DriverManager
        // fails BEFORE any HikariDataSource is created, so no pool leak.
        NocobaseDataSourceProperties.DataSourceConfig badConfig =
                new NocobaseDataSourceProperties.DataSourceConfig();
        badConfig.setUrl("jdbc:h2:tcp://localhost:19999/nosuchdb");
        badConfig.setDialect("h2");
        badConfig.setEnabled(true);
        dataSourceProperties.getDataSources().put("p0b-val-fail-ds", badConfig);

        try {
            DataSourceUnavailableException ex = assertThrows(
                    DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0b-val-fail-ds"),
                    "Preflight connection should fail");

            // Error message must be sanitized — no URL, host, port, password
            String msg = ex.getSanitizedReason();
            assertNotNull(msg);
            assertFalse(msg.toLowerCase().contains("jdbc:"),
                    "Error should not contain JDBC URL");
            assertFalse(msg.toLowerCase().contains("tcp:"),
                    "Error should not contain connection details");
            assertFalse(msg.toLowerCase().contains("19999"),
                    "Error should not contain port number");

            // Registry should NOT contain the failed key — no leaked holder
            assertThrows(DataSourceUnavailableException.class,
                    () -> resolver.resolve("p0b-val-fail-ds"),
                    "Subsequent resolve should still fail (key is marked unavailable)");

            // No HikariDataSource was ever created — no resource leak possible
        } finally {
            resolver.clearUnavailable();
            dataSourceProperties.getDataSources().remove("p0b-val-fail-ds");
        }
    }

    @Test
    @DisplayName("P0-B: Concurrent resolve of same key → only one external datasource created")
    void concurrentResolve_createsOnlyOneDatasource() throws Exception {
        // Use "reporting" datasource which is configured but not yet resolved
        int threadCount = 10;
        CountDownLatch startLatch = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);

        List<Future<JdbcTemplate>> futures = new ArrayList<>();
        for (int i = 0; i < threadCount; i++) {
            futures.add(executor.submit(() -> {
                startLatch.await(); // all threads wait for the signal
                return resolver.resolve("reporting");
            }));
        }

        // Signal all threads to start concurrently
        startLatch.countDown();

        // Collect results — all must return the same JdbcTemplate instance
        JdbcTemplate first = futures.get(0).get(30, TimeUnit.SECONDS);
        assertNotNull(first, "First resolve should return a valid JdbcTemplate");

        for (int i = 1; i < threadCount; i++) {
            JdbcTemplate template = futures.get(i).get(30, TimeUnit.SECONDS);
            assertSame(first, template,
                    "All concurrent resolves must return the same JdbcTemplate instance");
        }

        executor.shutdown();
    }

    @Test
    @DisplayName("P0-B: destroy() safe to call multiple times")
    void destroySafeToCallMultipleTimes() {
        // Create external datasources first
        resolver.resolve("analytics");
        resolver.resolve("reporting");

        // destroy() must be idempotent — no exceptions on repeated calls
        assertDoesNotThrow(() -> {
            resolver.destroy();
            resolver.destroy(); // second call should be safe (registry is empty)
            resolver.destroy(); // third call should also be safe
        }, "destroy() should be safe to call multiple times");
    }

    @Test
    @DisplayName("P0-B: clearUnavailable() safe to call multiple times")
    void clearUnavailableSafeToCallMultipleTimes() {
        // Create external datasources first
        resolver.resolve("analytics");
        resolver.resolve("reporting");

        // clearUnavailable() must be idempotent — no exceptions on repeated calls
        assertDoesNotThrow(() -> {
            resolver.clearUnavailable();
            resolver.clearUnavailable(); // second call should be safe (registry is empty)
            resolver.clearUnavailable(); // third call should also be safe
        }, "clearUnavailable() should be safe to call multiple times");
    }

    @Test
    @DisplayName("P0-B: Main datasource is unaffected by all cleanup operations")
    void mainDatasourceUnaffectedByAllOperations() {
        // Resolve the main datasource
        JdbcTemplate mainJdbc = resolver.resolve("main");
        DataSource mainDs = mainJdbc.getDataSource();
        assertNotNull(mainDs, "main DataSource should not be null");

        // Create external datasources to populate the registry
        resolver.resolve("analytics");
        resolver.resolve("reporting");

        // Call destroy() — external datasources closed, main must survive
        resolver.destroy();

        // Main datasource must still be usable
        assertDoesNotThrow(() -> {
            try (Connection conn = mainDs.getConnection()) {
                assertNotNull(conn);
                assertFalse(conn.isClosed(), "main datasource connection should be open");
            }
        }, "main datasource should remain open and usable after destroy()");

        // clearUnavailable() should also leave main untouched
        resolver.clearUnavailable();

        assertDoesNotThrow(() -> {
            try (Connection conn = mainDs.getConnection()) {
                assertNotNull(conn);
                assertFalse(conn.isClosed(),
                        "main datasource should remain open after clearUnavailable()");
            }
        }, "main datasource should remain open after clearUnavailable()");
    }

    // ═══════════════════════════════════════════════════════════════════
    // Helper methods
    // ═══════════════════════════════════════════════════════════════════

    private void authAsAdmin() {
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(1L, null, List.of()));
    }

    private void authAsMember() {
        if (memberUserId == null) fail("member user not created");
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(memberUserId, null, List.of()));
    }

    private void cleanupMemberPermissions(String resourceName) {
        Role memberRole = roleRepository.findByName("member").orElse(null);
        if (memberRole == null) return;

        String roleName = memberRole.getName();
        roleResourceRepository.findByRoleNameAndResourceName(roleName, resourceName)
                .ifPresent(rr -> {
                    List<RoleResourceScope> scopes = roleResourceScopeRepository.findByRoleResourceId(rr.getId());
                    roleResourceScopeRepository.deleteAll(scopes);
                    List<RoleResourceAction> actions = roleResourceActionRepository.findByRoleResourceId(rr.getId());
                    roleResourceActionRepository.deleteAll(actions);
                    roleResourceRepository.delete(rr);
                });
    }

    private void grantMemberPermission(String resourceName, String action, String fields) {
        Role memberRole = roleRepository.findByName("member").orElse(null);
        if (memberRole == null) fail("member role not found");

        String roleName = memberRole.getName();
        RoleResource rr = roleResourceRepository
                .findByRoleNameAndResourceName(roleName, resourceName)
                .orElseGet(() -> {
                    RoleResource newRr = new RoleResource(roleName, resourceName);
                    return roleResourceRepository.save(newRr);
                });

        RoleResourceAction rra = new RoleResourceAction(rr.getId(), action, fields);
        roleResourceActionRepository.save(rra);
    }

    private void grantMemberPermissionWithScope(String resourceName, String action, String fields, String scopeJson) {
        Role memberRole = roleRepository.findByName("member").orElse(null);
        if (memberRole == null) fail("member role not found");

        String roleName = memberRole.getName();
        RoleResource rr = roleResourceRepository
                .findByRoleNameAndResourceName(roleName, resourceName)
                .orElseGet(() -> {
                    RoleResource newRr = new RoleResource(roleName, resourceName);
                    return roleResourceRepository.save(newRr);
                });

        RoleResourceAction rra = new RoleResourceAction(rr.getId(), action, fields);
        roleResourceActionRepository.save(rra);

        RoleResourceScope scope = new RoleResourceScope(rr.getId(), scopeJson, action);
        roleResourceScopeRepository.save(scope);
    }
}