-- Flyway Baseline Migration V1
-- Captures all existing system tables for NocoBase Java backend
-- Uses quoted identifiers for case-sensitive compatibility with H2 PostgreSQL mode and PostgreSQL

-- Users table
CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "nickname" VARCHAR(255),
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Roles table
CREATE TABLE IF NOT EXISTS "roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "title" VARCHAR(255),
    "is_default" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User-Role join table
CREATE TABLE IF NOT EXISTS "user_roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "users"("id"),
    FOREIGN KEY ("role_id") REFERENCES "roles"("id")
);

-- Collections metadata table
CREATE TABLE IF NOT EXISTS "collections" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "title" VARCHAR(255),
    "namespace" VARCHAR(255),
    "table_name" VARCHAR(255),
    "schema" VARCHAR(255) DEFAULT 'public',
    "template" VARCHAR(255),
    "type" VARCHAR(50) DEFAULT 'physical',
    "view" BOOLEAN DEFAULT FALSE,
    "sql" TEXT,
    "inherits" TEXT,
    "category" VARCHAR(255),
    "sortable" BOOLEAN DEFAULT FALSE,
    "logging" BOOLEAN DEFAULT FALSE,
    "hidden" BOOLEAN DEFAULT FALSE,
    "system" BOOLEAN DEFAULT FALSE,
    "fields" TEXT,
    "options" TEXT,
    "auto_gen_id" BOOLEAN DEFAULT TRUE,
    "created_at" BOOLEAN DEFAULT TRUE,
    "updated_at" BOOLEAN DEFAULT TRUE,
    "created_at_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Fields metadata table
CREATE TABLE IF NOT EXISTS "fields" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "collection_name" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "interface_type" VARCHAR(50),
    "ui_schema" TEXT,
    "options" TEXT,
    "target" VARCHAR(255),
    "foreign_key" VARCHAR(255),
    "source_key" VARCHAR(255) DEFAULT 'id',
    "target_key" VARCHAR(255) DEFAULT 'id',
    "through" VARCHAR(255),
    "other_key" VARCHAR(255),
    "sort_order" INTEGER DEFAULT 0,
    "hidden" BOOLEAN DEFAULT FALSE,
    "system" BOOLEAN DEFAULT FALSE,
    "component" VARCHAR(255),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("collection_name") REFERENCES "collections"("name")
);

-- Application plugins table
CREATE TABLE IF NOT EXISTS "application_plugins" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "package_name" VARCHAR(255),
    "enabled" BOOLEAN DEFAULT FALSE,
    "installed" BOOLEAN DEFAULT FALSE,
    "built_in" BOOLEAN DEFAULT FALSE,
    "version" VARCHAR(50),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System settings table
CREATE TABLE IF NOT EXISTS "system_settings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "setting_key" VARCHAR(255) UNIQUE NOT NULL,
    "setting_value" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- UI Schemas table
CREATE TABLE IF NOT EXISTS "ui_schemas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uid" VARCHAR(255) NOT NULL,
    "schema_uid" VARCHAR(255),
    "name" VARCHAR(255),
    "schema" TEXT,
    "parent_uid" VARCHAR(255),
    "sort_order" INTEGER DEFAULT 0,
    "locked" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- UI Schema Templates table
CREATE TABLE IF NOT EXISTS "ui_schema_templates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "schema" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Role-Resource permissions
CREATE TABLE IF NOT EXISTS "role_resources" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(255) NOT NULL,
    "resource_name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Role-Resource-Action permissions
CREATE TABLE IF NOT EXISTS "role_resource_actions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_resource_id" BIGINT NOT NULL,
    "action" VARCHAR(50) NOT NULL,
    "fields" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("role_resource_id") REFERENCES "role_resources"("id")
);

-- Role-Resource-Scope (data range permissions)
CREATE TABLE IF NOT EXISTS "role_resource_scopes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_resource_id" BIGINT NOT NULL,
    "scope" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("role_resource_id") REFERENCES "role_resources"("id")
);

-- Role snippets
CREATE TABLE IF NOT EXISTS "role_snippets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(255) NOT NULL,
    "snippet" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Plugins table (legacy, for compatibility)
CREATE TABLE IF NOT EXISTS "plugins" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL,
    "package_name" VARCHAR(255),
    "version" VARCHAR(50),
    "description" TEXT,
    "enabled" BOOLEAN DEFAULT FALSE,
    "installed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_fields_collection_name" ON "fields"("collection_name");
CREATE INDEX IF NOT EXISTS "idx_fields_name" ON "fields"("name");
CREATE INDEX IF NOT EXISTS "idx_ui_schemas_parent_uid" ON "ui_schemas"("parent_uid");
CREATE INDEX IF NOT EXISTS "idx_ui_schemas_uid" ON "ui_schemas"("uid");
CREATE INDEX IF NOT EXISTS "idx_user_roles_user_id" ON "user_roles"("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_roles_role_id" ON "user_roles"("role_id");
CREATE INDEX IF NOT EXISTS "idx_role_resources_role_name" ON "role_resources"("role_name");
CREATE INDEX IF NOT EXISTS "idx_role_resources_resource_name" ON "role_resources"("resource_name");