-- V4: Add external_data_sources table for runtime data source configuration management
-- Supports CRUD operations via the DataSourceController API.
-- Secrets (ds_password) are stored encrypted/hashed and never returned to the frontend.
CREATE TABLE IF NOT EXISTS "external_data_sources" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ds_key" VARCHAR(64) UNIQUE NOT NULL,
    "display_name" VARCHAR(255),
    "ds_url" VARCHAR(1024) NOT NULL,
    "driver_class_name" VARCHAR(255),
    "ds_username" VARCHAR(255),
    "ds_password" VARCHAR(512),
    "enabled" BOOLEAN DEFAULT TRUE NOT NULL,
    "dialect" VARCHAR(50),
    "read_only" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_external_ds_key" ON "external_data_sources"("ds_key");