-- V6: Audit logs table
-- Records all sensitive write operations for security auditing.
-- Admin-only query API. Audit records never contain passwords, tokens,
-- secrets, SQL, JDBC URLs, or datasource passwords.

CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "actor_user_id" BIGINT,
    "action" VARCHAR(50) NOT NULL,
    "resource" VARCHAR(100) NOT NULL,
    "resource_key" VARCHAR(500),
    "details" TEXT,
    "status" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "request_id" VARCHAR(64)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS "idx_audit_logs_resource" ON "audit_logs"("resource");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_resource_key" ON "audit_logs"("resource", "resource_key");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_actor_user_id" ON "audit_logs"("actor_user_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_created_at" ON "audit_logs"("created_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_request_id" ON "audit_logs"("request_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_status" ON "audit_logs"("status");