package com.nocobase.web;

/**
 * Thread-local holder for the current request ID.
 * Set by {@link RequestIdFilter}, read by {@link com.nocobase.service.AuditLogService}.
 * <p>
 * Same request always gets the same requestId. If no request context is available,
 * a fallback UUID is generated by the filter.
 */
public final class RequestIdContext {

    private static final ThreadLocal<String> CURRENT_REQUEST_ID = new ThreadLocal<>();

    private RequestIdContext() {
        // utility class
    }

    /**
     * Set the current request ID for this thread.
     */
    public static void set(String requestId) {
        CURRENT_REQUEST_ID.set(requestId);
    }

    /**
     * Get the current request ID, or null if none is set.
     */
    public static String get() {
        return CURRENT_REQUEST_ID.get();
    }

    /**
     * Clear the request ID from the current thread.
     */
    public static void clear() {
        CURRENT_REQUEST_ID.remove();
    }
}